### ISSUE TITLE
ENV missing some entries

### ISSUE THREAD

**Issue by CallumAttryde** [kpalf/dockerfiles#12]
When using these images I found a couple of usability issues

- PYTHONPATH is not set (or appended to), meaning that all deriving images must set it up (typically ${APAMA_HOME}/third_party/python/lib/python2.7/site-packages) to be able to use the pysys extensions
- LD_LIBRARY_PATH does not contain ${APAMA_WORK}/lib, which is a common location for searching user created libraries for

Current workaround is to define both in deriving images, eg https://github.com/CallumAttryde/apama_file_transport/blob/master/Dockerfile

**Comment by kpalf** [comment]
This issue was resolved by
https://github.com/kpalf/dockerfiles/releases/tag/10.3.0.1

However, then the LD_LIBRARY_PATH openssl issue (issue #14) was noticed, and that is now fixed with 
https://github.com/kpalf/dockerfiles/releases/tag/10.3.0.1_fix1

The 10.3.0.1 images have been re-pushed to DockerHub with this latest fix applied, but no tag changes (i.e. updated existing tags).  Applies to CentOS/amd64, Ubuntu/amd64, Raspbian/ARMv7hf
